-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, CATEGORY
     , SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK AS B
     INNER JOIN AUTHOR AS A
     ON B.AUTHOR_ID = A.AUTHOR_ID
     INNER JOIN (SELECT *
                FROM BOOK_SALES
                ) AS S
                ON B.BOOK_ID = S.BOOK_ID
WHERE SALES_DATE LIKE "2022-01%"
GROUP BY B.AUTHOR_ID, CATEGORY
ORDER BY B.AUTHOR_ID, CATEGORY DESC