-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF AS F, JULY AS J
WHERE F.FLAVOR = J.FLAVOR
GROUP BY FLAVOR
HAVING SUM(F.TOTAL_ORDER + J.TOTAL_ORDER)
ORDER BY SUM(F.TOTAL_ORDER + J.TOTAL_ORDER) DESC
LIMIT 3;