-- 코드를 작성해주세요
WITH cte AS (
     SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
            MAX(SIZE_OF_COLONY) AS MAXSIZE
     FROM ecoli_data
     GROUP BY YEAR(DIFFERENTIATION_DATE)
     )
SELECT cte.YEAR, (cte.MAXSIZE - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ecoli_data
LEFT JOIN cte ON YEAR(DIFFERENTIATION_DATE) = cte.YEAR
ORDER BY cte.YEAR, (cte.MAXSIZE - SIZE_OF_COLONY);





