-- 코드를 입력하세요
SELECT DISTINCT(h.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS c
     JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h
     ON c.car_id = h.car_id
WHERE CAR_TYPE = '세단'
      AND START_DATE LIKE '2022-10%'
ORDER BY h.car_id DESC