-- 코드를 입력하세요
# SELECT *
# FROM USED_GOODS_BOARD
# WHERE (
#         SELECT *
#         FROM USED_GOODS_REPLY 
#         WHERE created_date LIKE '2022-10%'
#     )

# SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS,
#        DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
# FROM USED_GOODS_BOARD AS B
#      LEFT JOIN USED_GOODS_REPLY AS R
#      USING(board_id)
# WHERE B.created_date LIKE '2022-10%'
#       AND R.created_date LIKE '2022-10%'
# ORDER BY R.CREATED_DATE, B.TITLE

SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS,
        DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS B, USED_GOODS_REPLY AS R 
WHERE B.BOARD_ID = R.BOARD_ID
      AND B.CREATED_DATE LIKE '2022-10%'
ORDER BY R.CREATED_DATE, B.TITLE