-- 코드를 작성해주세요
WITH A AS (
     SELECT FISH_TYPE, 
     AVG(CASE WHEN LENGTH IS NULL THEN 10
         ELSE LENGTH END) AS LENGTH
     FROM FISH_INFO
     GROUP BY FISH_TYPE
     HAVING LENGTH >= 33
)

SELECT COUNT(*) AS FISH_COUNT
     , MAX(I.LENGTH) AS MAX_LENGTH
     , A.FISH_TYPE
FROM FISH_INFO I 
     INNER JOIN A
     ON I.FISH_TYPE = A.FISH_TYPE
GROUP BY FISH_TYPE
ORDER BY A.FISH_TYPE;